import { RouteInterface } from "../models";
import {
	SignIn,
	Dashboard,
	ProfilePage,
	SignOut,
	PullRequests,
	GitIssues,
	PresentationsOrWebinars,
	Blogs,
	Projects,
	ProjectTasks,
	NotFound,
	Interns,
	Roles,
	Home,
} from "../pages";
import {
	LOGOUT,
	LOGIN,
	PROFILE,
	GIT_ISSUES_PATH,
	PULL_REQUESTS_PATH,
	PRESENTATIONS_OR_WEBINARS_PATH,
	BLOGS_PATH,
	PROJECTS_PATH,
	PROJECT_TASKS_PATH,
	NOT_FOUND,
	INTERNS,
	ROLES_PATH,
	DASHBOARD,
	HOME,
} from "../constants";
import {
	AccountCircleOutlined,
	ErrorOutline,
	SlideshowOutlined,
	DashboardOutlined,
	PlaylistAddCheckOutlined,
	CreateOutlined,
	WorkOutlineOutlined,
	LowPriorityOutlined,
	PeopleOutlineOutlined,
	AssignmentIndOutlined,
} from "@material-ui/icons";
import React from "react";

export const routes: RouteInterface[] = [
	{
		component: Dashboard,
		path: DASHBOARD,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Dashboard",
		appLayout: true,
		permission: ["mentor", "intern"],
		icon: <DashboardOutlined />,
	},
	{
		component: SignIn,
		path: LOGIN,
		showOnMenu: false,
		protected: false,
		exact: true,
		name: "Login",
		appLayout: false,
		permission: "all",
	},
	{
		component: SignOut,
		path: LOGOUT,
		protected: true,
		exact: true,
		name: "Logout",
		showOnMenu: false,
		appLayout: false,
		permission: "all",
	},
	{
		component: ProfilePage,
		path: PROFILE,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Profile",
		appLayout: true,
		permission: "intern",
		icon: <AccountCircleOutlined />,
	},
	{
		component: GitIssues,
		path: GIT_ISSUES_PATH,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Git Issues",
		appLayout: true,
		permission: "intern",
		icon: <ErrorOutline />,
	},
	{
		component: PullRequests,
		path: PULL_REQUESTS_PATH,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Pull Requests",
		appLayout: true,
		permission: "intern",
		icon: <LowPriorityOutlined />,
	},
	{
		component: PresentationsOrWebinars,
		path: PRESENTATIONS_OR_WEBINARS_PATH,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Presentations/Webinars",
		appLayout: true,
		permission: "intern",
		icon: <SlideshowOutlined />,
	},
	{
		component: Blogs,
		path: BLOGS_PATH,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Blogs",
		appLayout: true,
		permission: "intern",
		icon: <CreateOutlined />,
	},
	{
		component: Projects,
		path: PROJECTS_PATH,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Projects",
		appLayout: true,
		permission: "intern",
		icon: <WorkOutlineOutlined />,
	},
	{
		component: ProjectTasks,
		path: PROJECT_TASKS_PATH,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Project Tasks",
		appLayout: true,
		permission: "intern",
		icon: <PlaylistAddCheckOutlined />,
	},
	{
		component: NotFound,
		path: NOT_FOUND,
		showOnMenu: false,
		protected: true,
		exact: false,
		name: "Not Found",
		appLayout: true,
		permission: "all",
	},
	{
		component: Interns,
		path: INTERNS,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Interns",
		appLayout: true,
		permission: "mentor",
		icon: <PeopleOutlineOutlined />,
	},
	{
		component: Roles,
		path: ROLES_PATH,
		showOnMenu: true,
		protected: true,
		exact: false,
		name: "Roles",
		appLayout: true,
		permission: "admin",
		icon: <AssignmentIndOutlined />,
	},
	{
		component: Home,
		path: HOME,
		showOnMenu: false,
		protected: true,
		exact: false,
		name: "Home",
		appLayout: true,
		permission: "all",
	},
];
