import Box from "./box.svg";
import Search from "./search.svg";
import Morning from "./morning.svg";
import Noon from "./sun.svg";
import Evening from "./beach.svg";
import Night from "./night.svg";
import Intern from "./worker.svg";
import GitIssue from "./alert.svg";
import PullRequest from "./exercise.svg";
import Presentation from "./chart.svg";
import Project from "./project.svg";
import Blog from "./blog.svg";
import NotFound from "./404.svg";
import Login from "./mobile-login.svg";

export const BoxGraphic = Box;
export const SearchGraphic = Search;
export const MorningGraphic = Morning;
export const NoonGraphic = Noon;
export const EveningGraphic = Evening;
export const NightGraphic = Night;
export const InternGraphic = Intern;
export const GitIssueGraphic = GitIssue;
export const PullRequestGraphic = PullRequest;
export const PresentationGraphic = Presentation;
export const ProjectGraphic = Project;
export const BlogGraphic = Blog;
export const NotFoundGraphic = NotFound;
export const LoginGraphic = Login;
