# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
            
    - name: Build Project
      env:
        REACT_APP_CLIENT_ID: ${{secrets.GAPI_CLIENT_ID}}
        REACT_APP_API_KEY: ${{secrets.GAPI_API_KEY}}
      run: |
        npm ci
        REACT_APP_CLIENT_ID="%REACT_APP_CLIENT_ID" REACT_APP_API_KEY="%REACT_APP_API_KEY" npm run build --if-present
   
    - name: Install Firebase
      env: 
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --token "%FIREBASE_TOKEN" --only hosting --non-interactive
        if: github.event_name=='push' 
        
    - name: Bump version
      run: |
        git config --global user.email "theviyanthan@outlook.com"
        git config --global user.name "Thivi"
        npm version patch
        if: github.event_name=='push'
