# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master]
    paths-ignore: 
      - 'package.json'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GIT_TOKEN_ACTON}}
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Bump version
      run: |
        git config --global user.email "version.bump@github.action.com"
        git config --global user.name "GitHub Action Version Bumping"
        npm version patch
        git push
      if: github.event_name=='push'
